### ISSUE TITLE
.NET 6 Crash, Xenko.Engine 3.2.0.1-beta01, Xenko.Updater.UpdateEngine.Run on UpdateOperationType.EnterObjectProperty

### ISSUE THREAD

**Issue by Tyler-IN** [DW2MC/DW2ModLoader#2]
There's a bug in Xenko.Engine 3.2.0.1-beta01 I've tracked down that has some invalid state (technically valid IL that sets up an invalid state).
I could fix by just recompiling it or I can just harmony patch it... going to go for the latter because the NuGet package for v3.2.0.1-beta01 has disappeared.

The bug has to do with animation setup, mostly affects the Gravillex or other space creatures when you zoom in on them and their wiggly bits are visible. It's technically not a valid state even under .NET Fw 4 but it "works" there anyway, while .NET 6 catches it and throws an exception.

The offending code happens before or on IL_00A9 of Xenko.Updater.UpdateEngine.Run, a managed GC heap pointer is pushed to the stack and then the case UpdateOperationType.EnterObjectProperty: is taken; either the loading of the pinned GC ref or the dereference of that pointer to get it's member causes an illegal program exception.

its technically not valid to pin the type it's coded to pin in the way it's trying to but I don't know if that's the actual problem.

**Comment by Mavor** [comment]
Definitely the Harmony patch way to go would be best. Postfix that shit ;P

**Comment by Tyler-IN** [comment]
Patched in https://github.com/DW2MC/DW2ModLoader/commit/ffafe7b97496b04616d616ac02b69d05769441e6

Latest v1.0.6 has fix incorporated.
